[build]
  base = "theme/"
  publish = "dist/"
  command = "npm run build"


[[redirects]]
from = "https://selfimprovingbooks.netlify.app/*"
to = "https://selfimprovingbooks.com/:splat"
status = 301
force = true
