[build]
  base = "theme/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
from = "https://selfimprovingbooks.netlify.app/*"
to = "https://selfimprovingbooks.com/:splat"
status = 301
force = true

[[redirects]]
from = "/topics/categories/economics"
to = "/categories/economics"
status = 301
force = true

[[redirects]]
from = "/topics"
to = "/"
status = 301
force = true

[[redirects]]
from = "/topics/categories/sports-and-outdoors"
to = "/categories/sports-and-outdoors"
status = 301
force = true

[[redirects]]
from = "/topics/categories/motivational"
to = "/categories/motivational"
status = 301
force = true

[[redirects]]
from = "/topics/categories/success"
to = "/categories/success"
status = 301
force = true
